[build]
  command = "python Backend/api/manage.py collectstatic --noinput && python Backend/api/manage.py migrate"
  publish = "Backend/api/staticfiles"

[build.environment]
  DJANGO_SECRET_KEY = "your_secret_key"
  DJANGO_DEBUG = "False"
  DJANGO_ALLOWED_HOSTS = "your_domain.com"
  DJANGO_DB_NAME = "your_db_name"
  DJANGO_DB_USER = "your_db_user"
  DJANGO_DB_PASSWORD = "your_db_password"
  DJANGO_DB_HOST = "your_db_host"
  DJANGO_DB_PORT = "your_db_port"
  CELERY_BROKER_URL = "redis://localhost:6379/0"
  CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
